apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.serviceAccountName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.app.serviceRole }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.app.serviceRoleBinding }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.app.serviceRole }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.app.serviceAccountName }}
    namespace: {{ .Values.namespace | default .Release.Namespace }}
