apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
